import pyautogui as py
py.press("win")
py.write("chrome")
py.press("enter")
py.sleep(2)
py.write("senai americana")
py.press("enter")
py.sleep(2)
py.click(313,547, button="left")
py.sleep(4)
py.click(1431,868, button="left")
py.sleep(2)
py.click(235,580, button="left")
py.sleep(2)
py.press("enter")
py.vscroll(-400)
#print(py.position())